### ISSUE TITLE
Glasses OBJ file

### ISSUE THREAD

**Issue by gauravgola96** [myxozoa/glasses_computer-vision#5]
Hey @myxozoa,

I am new to OpenGL and this project is awesome.  
can you please provide sample glasses .obj and .mlt file. Also a short write up about the flow of the code.

**Comment by myxozoa** [comment]
Hey thanks, this is the first thing I ever really made with python, OpenGL or OpenCV so I'm not sure how helpful it would be.

All the .obj and .mtl files I used at the time are in the assets folder.  You can switch between them by changing the `MODEL `constant in constants.py.

I never ended up making any glasses models or anything.  I put this project down right as I got a new job. Although this makes me want to pick it back up again.

The flow of the code is relatively straightforward, just a while loop that calls a draw function (`Glasses.draw` in main.py).  All of the slightly more complicated stuff is for computer vision with OpenCV, which is mostly just managing different data formats etc.

Here's a very high level overview that might help provide some guidance.

Upon starting `Glasses.main` is called and handles these three things:

1. Setting up the GUI window, all the OpenGL buffers needed and loading the model/shaders
2. Looping the `Glasses.draw` function
3. Cleaning up all the stuff in memory and releasing the webcam

The `Glasses.draw` function sequentially works like this:

1. Clears the necessary buffers (`glClear`)
2. Draws a single frame from the webcam to the screen (with `self.webcam.get_current_frame()` and     `self.draw_webcam(image)`)
3. Attempts to see if there is a face present, and calculates its orientation in space (with `self.solver.reproject(image)`)
4. Sets up view/projection matrices that very roughly match my webcam (with `glm.perspective` etc)
5. Positions and scales the model to roughly match the face found (with `glm.translate` `glm.scale`)
6. Pass light information to the shader (with `glUniform3fv`) (very rough I just didnt want it looking flat)
7. Actually draws the model over the webcam drawn earlier.  It's on top just because it happens afterwards (with `glDrawArrays`)

**Comment by gauravgola96** [comment]
Hey @myxozoa,
Thanks for such a detailed explanation regarding the code.

**Comment by gauravgola96** [comment]
Hey @myxozoa , 
Can you explain how you are deciding location of rendering on face?  
As far as I understand you are deciding something in view matrix. How can we put object on a specific location on face. 
Thanks in advance
